[package]
name = "tokio_stream_file"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
tokio = { version = "1.44.1", features = ["full"] }
