[package]
name = "tokio_select"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0"
tokio = { version = "1.44.1", features = ["full"] }
